### ISSUE TITLE
Transformation changes evalution order of code.

### ISSUE THREAD

**Issue by retronym** [monadless/monadless#61] opened 2020-06-29 05:13 UTC
Thanks for the pointer to `monadless`. I've been trying it out and noted that:

```
scala> lift { (unlift(Option.empty[String]), unlift(???)) } // expected `None`

scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:288)
  ... 36 elided
```

Expected `None`

```
scala> def i(i: Int) = { println(i); Some(i) }

scala> lift { (unlift(i(1)), i(2).get, unlift(i(3))) }

1
3
2
res14: Option[(Int, Int, Int)] = Some((1,2,3))
```

Expected `1\n2\n\3`

```
scala> lift { object O { def x = unlift(i(2)) }; i(1).getOrElse(O.x) }
2
1
res19: Option[Int] = Some(1)
```

**Comment by fwbrasil** [comment] 2020-07-25 15:39
That’s because Monadless favors an applicative transformation (something scala-async doesn’t support). It’s a reasonable default since a use case like you describe, where the user would mix side effects and monadic composition isn’t a common use case. That said, it should be easy to support strictly sequential execution. I’ll close the issue since the behavior is by design. I’ll reconsider if we encounter real-world bug report

**Closed as completed by fwbrasil** 2020-07-25 15:39 UTC
